---
title: Analysis script
subtitle: Oddball with Cognitive model
author:
- Mathias Sablé-Meyer
date: 1st Semester 2019
lang: en
output:
  tufte::tufte_html:
    smart: true
    toc: true
    toc_depth: 1
---

```{r someTools, echo = FALSE, cache = FALSE, message=FALSE}
# This loads packages and install them if need be:
if (!require("pacman")) install.packages("pacman")
pacman::p_load(ggplot2,
               ggExtra,
               ggthemes,
               reshape2,
               jsonlite,
               tibble,
               stringr,
               tufte,
               knitr,
               pander,
               magrittr,
               tidyr,
               plyr,
               dplyr,
               grid,
               broom,
               ggrepel,
               magick,
               cowplot,
               tlm,
               parsedate,
               scales,
               png,
               lme4,
               ggimage,
               mixtools,
               PerformanceAnalytics,
               corrplot,
	    Hmisc,
               kableExtra, install = TRUE)

options(knitr.table.format = "html",
        knitr.table.booktabs = TRUE,
        knitr.kable.NA = '')

knitr::opts_chunk$set(fig.lp  = '')
knitr::opts_chunk$set(cache   = FALSE)
knitr::opts_chunk$set(autodep = TRUE)
knitr::opts_chunk$set(autodep = TRUE)
knitr::opts_chunk$set(echo    = FALSE)
#knitr::opts_chunk$set(results = 'asis')
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(error = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(tidy = TRUE)

#accent <- "#B21512"
#second <- "#096BB2"
#color1 <- "#B21512"
#color2 <- "#096BB2"
bg     <- "#ffffff"

nothing <- "$\\varnothing{}$"

myTheme <- theme_get() +
           theme(panel.background = element_rect(fill = bg),
                 text = element_text(size=15),
                 legend.background = element_rect(fill = bg),
                 plot.background = element_rect(fill = bg)) +
	   theme(axis.text.y=element_text(colour="black")) +
	   theme(axis.text.x=element_text(colour="black"))
theme_set(myTheme)

## Let's not print too many digits for the human eye
options(digits=3)
panderOptions("digits", 2)
panderOptions("missing", "")
panderOptions("table.style", "rmarkdown")
panderOptions("table.split.table", "Inf")

list <- structure(NA,class="result")
"[<-.result" <- function(x,...,value) {
   args <- as.list(match.call())
   args <- args[-c(1:2,length(args))]
   length(value) <- length(args)
   for(i in seq(along=args)) {
     a <- args[[i]]
     if(!missing(a)) eval.parent(substitute(a <- v,list(a=a,v=value[[i]])))
   }
   x
}
se <- function(x) {
  sd(x) / sqrt(length(x))
}
```

```{r}
shapesInOrder <- c("square", "losange", "rectangle", "parallelogram", "isoTrapezoid", "trapezoid", "rightKite", "kite", "hinge", "rustedHinge", "random", "catOrBird", "train")

pngs <- list(rasterGrob(readPNG("res/square.png"), interpolate=TRUE)
            ,rasterGrob(readPNG("res/losange.png"), interpolate=TRUE)
            ,rasterGrob(readPNG("res/rectangle.png"), interpolate=TRUE)
            ,rasterGrob(readPNG("res/parallelogram.png"), interpolate=TRUE)
            ,rasterGrob(readPNG("res/isoTrapezoid.png"), interpolate=TRUE)
            ,rasterGrob(readPNG("res/trapezoid.png"), interpolate=TRUE)
            ,rasterGrob(readPNG("res/rightKite.png"), interpolate=TRUE)
            ,rasterGrob(readPNG("res/kite.png"), interpolate=TRUE)
            ,rasterGrob(readPNG("res/hinge.png"), interpolate=TRUE)
            ,rasterGrob(readPNG("res/rustedHinge.png"), interpolate=TRUE)
            ,rasterGrob(readPNG("res/random.png"), interpolate=TRUE))

pngs_target <- list("res/square.png"
            ,"res/losange.png"
            ,"res/rectangle.png"
            ,"res/parallelogram.png"
            ,"res/isoTrapezoid.png"
            ,"res/trapezoid.png"
            ,"res/rightKite.png"
            ,"res/kite.png"
            ,"res/hinge.png"
            ,"res/rustedHinge.png"
            ,"res/random.png")

pngs_train <- list("res/pair1_tile-1.png",
                   "res/pair2_tile-1.png",
                   "res/pair3_tile-1.png",
                   "res/pair4_tile-1.png",
                   "res/pair5_tile-1.png",
                   "res/pair6_tile-1.png",
                   "res/pair7_tile-1.png",
                   "res/pair8_tile-1.png",
                   "res/pair9_tile-1.png",
                   "res/pair10_tile-1.png",
                   "res/imagened.png")
pngs_all <- c(pngs_target,
              "res/imagened.png",
              "res/pair1_tile-1.png")
```

```{r}
french <- read.csv("french.csv") %>%
  select(-X, -sd) %>%
  mutate(layer = "french")
himbas <- read.csv("himbas.csv") %>%
  select(-X, -sd) %>%
  mutate(layer = "himbas")
```

```{r}

m_french <- french  %>%
  select(mean) %>%
  summarize_all(mean) %$%
  mean

json <- fromJSON("./result.json", flatten=T)
num_repetition <- json$num_repetition
d <- json[2:12] %>%
  unlist %>%
  enframe %>%
  separate(name, into = c(paste0("x", 1:3))) %>%
  rename(shape = x1, stim_5 = x2, stim_1 = x3, average = value) %>%
  mutate(direction = ifelse(stim_5 == 0, 0, 1)) %>%
  group_by(shape) %>%
  select(-direction,-stim_1,-stim_5) %>%
  summarize_all(funs(mean,se)) %>%
  mutate(se = sqrt((mean*(1-mean))/num_repetition),
         layer = "model1") %>%
  ungroup
m_model <- d %>%
  select(mean) %>%
  summarize_all(mean) %$%
  mean
p <- d %>%
  rbind(french) %>%
  mutate(shape = factor(shape, levels = shapesInOrder)) %>%
  ggplot(aes(y = mean, x = layer, fill = shape)) +
  geom_bar(stat="identity", width=0.8, position=position_dodge(width=0.8)) +
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se),width=0, position=position_dodge(width=0.8)) +
  ylim(0,1) +
  geom_hline(aes(yintercept=m_model), size=0.1) +
  annotate("text", y = m_model + 0.025, x = 2.1, label="Model1 mean", size=4.3) +
  geom_hline(aes(yintercept=m_french), size=0.1) +
  annotate("text", y = m_french - 0.025, x = 1.1, label="French mean", size=4.3) +
  geom_hline(yintercept=1/6) +
  xlab("Model") + ylab("Success Rate") +
  theme(legend.text=element_text(size=45)) +
  scale_fill_discrete(name="Shape", labels=rep("     ",22)) +
  annotate("text", y = 1/6 + 0.025, x = 2, label="Chance Level", size=4.3)

draw_legend <- function(pl, l, s, xmin, ymax, dy) {
  i <- 0
  for (f in l) {
    pl <- ggdraw(pl) +
      draw_image(f, x = xmin, y = ymax-(i*dy), width = s)
    i <- i + 1
  } 
  return(pl)
}

p <- draw_legend(p, pngs_target, 0.04, 0.92, 0.385, 0.0735)
p +
  ggsave(filename = "/tmp/model1.pdf", width = 40/3, height = 20/3)
```

