---
title: Analysis script
subtitle: Oddball with Cognitive model
author:
- Mathias Sablé-Meyer
date: 1st Semester 2019
lang: en
output:
  tufte::tufte_html:
    smart: true
    toc: true
    toc_depth: 1
---

```{r someTools, echo = FALSE, cache = FALSE, message=FALSE}
# This loads packages and install them if need be:
if (!require("pacman")) install.packages("pacman")
pacman::p_load(ggplot2,
               ggthemes,
               reshape2,
               jsonlite,
               tufte,
               knitr,
               pander,
               plyr,
               dplyr,
               magrittr,
               tibble,
               tidyr,
               grid,
               broom,
               cowplot,
               png,
               ggimage,
               #kableExtra,
               install = TRUE)

knitr::opts_chunk$set(cache   = FALSE)
knitr::opts_chunk$set(autodep = TRUE)
knitr::opts_chunk$set(echo    = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(error = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(tidy = TRUE)

bg     <- "#fffff8"

myTheme <- theme_get() +
           theme(panel.background = element_rect(fill = bg),
                 legend.background = element_rect(fill = bg),
                 plot.background = element_rect(fill = bg)) +
            theme(axis.text.y=element_text(colour="black")) +
            theme(axis.text.x=element_text(colour="black"))

theme_set(myTheme)

## Let's not print too many digits for the human eye
options(digits=3)
se <- function(x) {
  sd(x) / sqrt(length(x))
}
```

```{r}
french <- read.csv("../behavioural_data/french.csv") %>%
  select(-X, -sd) %>%
  mutate(layer = "french")
shapesInOrder <- c("square", "losange", "rectangle", "parallelogram", "isoTrapezoid", "trapezoid", "rightKite", "kite", "hinge", "rustedHinge", "random", "catOrBird", "train")
```

# Comparison of bar plots

```{r}
m_french <- french  %>%
  select(mean) %>%
  summarize_all(mean) %$%
  mean

model1 <- read.csv("best_model1.csv")
model2 <- read.csv("best_model2.csv")
num_rep1 <- 2 * (model1$num_rep[1])
num_rep2 <- 2 * (model2$num_rep[1])
d1 <- model1 %>%
  select(-mostlyRegularShapes, -num_rep) %>%
  group_by(shape) %>%
  summarize_all(mean) %>%
  mutate(layer = "model1",
         se = sqrt(mean*(1 - mean))/sqrt(num_rep1)) %>%
  ungroup
d2 <- model2 %>%
  select(-mostlyRegularShapes, -num_rep) %>%
  group_by(shape) %>%
  summarize_all(mean) %>%
  mutate(layer = "model2",
         se = sqrt(mean*(1 - mean))/sqrt(num_rep2)) %>%
  ungroup

m_model1 <- d1 %>%
  select(mean) %>%
  summarize_all(mean) %$%
  mean

m_model2 <- d2 %>%
  select(mean) %>%
  summarize_all(mean) %$%
  mean

```

```{r}
d1 %>%
  rbind(french) %>%
  mutate(shape = factor(shape, levels = shapesInOrder,)) %>%
  ggplot(aes(y = mean, x = layer, fill = shape)) +
  geom_bar(stat="identity", width=0.8, position=position_dodge(width=0.8)) +
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se),width=0, position=position_dodge(width=0.8)) +
  ylim(0,1) +
  geom_hline(aes(yintercept=m_model1), size=0.1) +
  annotate("text", y = m_model1 + 0.025, x = 2.1, label="Model1 mean", size=4.3) +
  geom_hline(aes(yintercept=m_french), size=0.1) +
  annotate("text", y = m_french - 0.025, x = 1.1, label="French mean", size=4.3) +
  geom_hline(yintercept=1/6) +
  xlab("Model") + ylab("Success Rate") +
  annotate("text", y = 1/6 + 0.025, x = 2, label="Chance Level", size=4.3)
```

```{r}
d2 %>%
  rbind(french) %>%
  mutate(shape = factor(shape, levels = shapesInOrder,)) %>%
  ggplot(aes(y = mean, x = layer, fill = shape)) +
  geom_bar(stat="identity", width=0.8, position=position_dodge(width=0.8)) +
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se),width=0, position=position_dodge(width=0.8)) +
  ylim(0,1) +
  geom_hline(aes(yintercept=m_model2), size=0.1) +
  annotate("text", y = m_model2 + 0.025, x = 2.1, label="Model2 mean", size=4.3) +
  geom_hline(aes(yintercept=m_french), size=0.1) +
  annotate("text", y = m_french - 0.025, x = 1.1, label="French mean", size=4.3) +
  geom_hline(yintercept=1/6) +
  xlab("Model") + ylab("Success Rate") +
  annotate("text", y = 1/6 + 0.025, x = 2, label="Chance Level", size=4.3)
```

# Correlation : plot and parameters

```{r}
d1 %>%
  rbind(french) %>%
  mutate(shape = factor(shape, levels = shapesInOrder,)) %>%
  select(shape,mean, layer) %>%
  group_by(shape) %>%
  spread(key="layer", value="mean") %>%
  ggplot(aes(x = french, y = model1)) +
  geom_smooth(method="lm") +
  geom_point()
```

```{r}
d2 %>%
  rbind(french) %>%
  mutate(shape = factor(shape, levels = shapesInOrder,)) %>%
  select(shape,mean, layer) %>%
  group_by(shape) %>%
  spread(key="layer", value="mean") %>%
  ggplot(aes(x = french, y = model2)) +
  geom_smooth(method="lm") +
  geom_point()
```

```{r}
d1 %>%
  rbind(french) %>%
  mutate(shape = factor(shape, levels = shapesInOrder,)) %>%
  select(shape,mean, layer) %>%
  group_by(shape) %>%
  spread(key="layer", value="mean") %>%
  lm(french ~ model1, data=.) %>%
  summary %>%
  pander
d2 %>%
  rbind(french) %>%
  mutate(shape = factor(shape, levels = shapesInOrder,)) %>%
  select(shape,mean, layer) %>%
  group_by(shape) %>%
  spread(key="layer", value="mean") %>%
  lm(french ~ model2, data=.) %>%
  summary %>%
  pander
```

